name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@51c0d5922252eab2cb7349f2142160df023fb656
        with:
          ruby-version: .ruby-version

      - name: Install gems
        run: |
          # Extract the exact versions of the rubocop gems from Gemfile.lock
          rubocop_version=$(sed -n -E 's/^    rubocop \((.+)\)/\1/p' Gemfile.lock)
          rubocop_minitest_version=$(sed -n -E 's/^    rubocop-minitest \((.+)\)/\1/p' Gemfile.lock)
          rubocop_performance_version=$(sed -n -E 's/^    rubocop-performance \((.+)\)/\1/p' Gemfile.lock)
          
          gem install rubocop -v $rubocop_version
          gem install rubocop-minitest -v $rubocop_minitest_version
          gem install rubocop-performance -v $rubocop_performance_version

      - name: Run Rubocop
        run: rubocop --except Metrics
